### ISSUE TITLE
Disable Bitlocker encryption if a BIOS update is found

### ISSUE THREAD

**Issue by julrich-usgs** [julrich-usgs/nofips-dell-drivers#2]
Something similar to:

suspend-bitlocker -mountpoint "C:" -rebootcount 1

When I have a chance to revisit this, I will add some kind of detection mechanism for bitlocker enabled systems so it disables bitlocker before rebooting. 

Most (maybe all?) systems will have problems on reboot with a bios update if TPM is enabled and in-use.

**Comment by A9G-Data-Droid** [comment]
Suspending bitlocker should be easy. I have an example in my new branch: https://github.com/A9G-Data-Droid/nofips-dell-drivers/tree/SuspendBitlocker

Before we can do this we need to detect when the update is a BIOS update. How do we do that?

**Comment by A9G-Data-Droid** [comment]
I answered my own question. My new branch will attempt to detect BIOS updates and suspend BitLocker if found. I can't test this right now so I'm not going to open a PR until I get it tested. Feel free to take a look and go for a spin.

**Comment by A9G-Data-Droid** [comment]
I have now tested my code on BitLocked systems. This updater is working great, I use it all the time.
